// GET Job Detail
export const GET_JOB_DETAIL_REQUEST = 'JobDetail/GET_JOB_DETAIL_REQUEST';
export const GET_JOB_DETAIL_SUCCESS = 'JobDetail/GET_JOB_DETAIL_SUCCESS';
export const GET_JOB_DETAIL_FAILED = 'JobDetail/GET_JOB_DETAIL_FAILED';

// DELETE Job
export const DELETE_JOB_REQUEST = 'JobDetail/DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS = 'JobDetail/DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILED = 'JobDetail/DELETE_JOB_FAILED';
