// GET Job Application
export const GET_JOB_APPLICATION_REQUEST = 'GET_JOB_APPLICATION_REQUEST';
export const GET_JOB_APPLICATION_SUCCESS = 'GET_JOB_APPLICATION_SUCCESS';
export const GET_JOB_APPLICATION_FAILED = 'GET_JOB_APPLICATION_FAILED';

// DELETE Job Application
export const DELETE_JOB_APPLICATION_REQUEST = 'DELETE_JOB_APPLICATION_REQUEST';
export const DELETE_JOB_APPLICATION_SUCCESS = 'DELETE_JOB_APPLICATION_SUCCESS';
export const DELETE_JOB_APPLICATION_FAILED = 'DELETE_JOB_APPLICATION_FAILED';
