export const GET_JOB_APPLICATION_REQUEST = 'GET_JOB_APPLICATION_REQUEST';
export const GET_JOB_APPLICATION_SUCCESS = 'GET_JOB_APPLICATION_SUCCESS';
export const GET_JOB_APPLICATION_FAILED = 'GET_JOB_APPLICATION_FAILED';
